version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend-api
    ports:
      - "3300:3300"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
